# Generated by Django 5.2.1 on 2025-06-02 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vendor or manufacturer name.', max_length=300, unique=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_of_life_announced_date', models.DateField(blank=True, help_text="Date the product's End-of-Life was announced.", null=True)),
                ('end_of_life_date', models.DateField(blank=True, help_text='Final date of support (End-of-Life).', null=True)),
                ('end_of_engineering_date', models.DateField(blank=True, help_text='Date when the software package was officially declared End-of-Engineering.', null=True)),
                ('end_of_sale_date', models.DateField(blank=True, help_text='Date when the product was officially declared End-of-Sale.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='OS/Software/firmware name.', max_length=300)),
                ('vendor', models.ForeignKey(help_text='Vendor or manufacturer of the software package.', on_delete=django.db.models.deletion.CASCADE, related_name='software_packages', to='eol.vendor')),
            ],
            options={
                'verbose_name': 'Software Package',
                'verbose_name_plural': 'Software Packages',
                'ordering': ['vendor__name', 'name'],
                'indexes': [models.Index(fields=['vendor', 'name'], name='eol_softwar_vendor__51c9ef_idx')],
                'unique_together': {('vendor', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_of_life_announced_date', models.DateField(blank=True, help_text="Date the product's End-of-Life was announced.", null=True)),
                ('end_of_life_date', models.DateField(blank=True, help_text='Final date of support (End-of-Life).', null=True)),
                ('end_of_engineering_date', models.DateField(blank=True, help_text='Date when the software package was officially declared End-of-Engineering.', null=True)),
                ('end_of_sale_date', models.DateField(blank=True, help_text='Date when the product was officially declared End-of-Sale.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Product name.', max_length=300)),
                ('vendor', models.ForeignKey(help_text='Vendor or manufacturer of the product.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='eol.vendor')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['vendor__name', 'name'],
                'indexes': [models.Index(fields=['vendor', 'name'], name='eol_product_vendor__eed476_idx')],
                'unique_together': {('vendor', 'name')},
            },
        ),
    ]
